# Define custom function directory
ARG FUNCTION_DIR="/function"

# Use a slim version of the base Python image to reduce the final image size
FROM python:3.12-slim

# Include global arg in this stage of the build
ARG FUNCTION_DIR


# Copy function code
RUN mkdir -p ${FUNCTION_DIR}
COPY . ${FUNCTION_DIR}

RUN apt-get update
RUN apt-get -y install git build-essential cmake wget tar

# Set working directory to function root directory
WORKDIR ${FUNCTION_DIR}

